### ISSUE TITLE
Getting error on Android

### ISSUE THREAD

**Issue by Kampeone** [yfuks/react-native-action-sheet#13]
I'm getting an error 'undefined is not an object (evaluating 'reactNativeActionSheet2.default.showActionSheetWithOptions)' when calling ActionSheet.showActionSheetWithOptions as shown in the example.

**Comment by yfuks** [comment]
What is your React-native version ?

**Comment by Kampeone** [comment]
0.46.1

**Comment by yfuks** [comment]
And your version of this package ?

**Comment by jesster2k10** [comment]
I solved this issue, the problem was that the library wasn't linked properly meaning that anytime you called that function it would return undefined as it had no idea what you were referring to.

Long story short, 

ensure you've linked the app properly. Sometimes automatic linking doesn't work so double check it's successful by doing it manually
