### ISSUE TITLE
[Android] Font size is too big...?

### ISSUE THREAD

**Issue by replecta** [yfuks/react-native-action-sheet#22]
Nice library, however i think the font size on android is too big.
Any way to change it by option or something?

**Comment by danielpgauer** [comment]
+1

**Comment by userbq201** [comment]
+1

**Comment by yfuks** [comment]
Hello !

Definitely possible. Have no time to get into it actually. Would gladly accept `PR` !

Since this module is kind of a fork from [react-native-image-picker](https://github.com/react-community/react-native-image-picker#android-optional) i highly recommend to look at how it is implemented:

https://github.com/react-community/react-native-image-picker#android-optional

**Comment by yfuks** [comment]
It was mutch more simple that expected, available in `0.0.5`

see [README](https://github.com/yfuks/react-native-action-sheet#optional-style-customization) for more informations

**Comment by danielpgauer** [comment]
forgot to bump version in package.json
