### ISSUE TITLE
Getting Error in Android

### ISSUE THREAD

**Issue by luco** [yfuks/react-native-action-sheet#8]
I'm getting this error on Android. On iOS works fine.

![image](https://user-images.githubusercontent.com/246373/27048007-87f1c210-4f80-11e7-9ed7-df3ed3bd666a.png)

Any thoughts?

**Comment by yfuks** [comment]
Can you paste your js code ?

**Comment by jesster2k10** [comment]
I solved this issue, the problem was that the library wasn't linked properly meaning that anytime you called that function it would return undefined as it had no idea what you were referring to.

Long story short, 

ensure you've linked the app properly. Sometimes automatic linking doesn't work so double check it's successful by doing it manually
